version: "3.7"

services:
  mongo:
    container_name: mongo
    image: bitnami/mongodb:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
